version: "3"

services:
  mysql:
    container_name: "homepage_mysql"
    restart: always
    image: mysql:5.7
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: homepage
      MYSQL_USER: homepage
      MYSQL_PASSWORD: homepage2021
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --skip-character-set-client-handshake
